name: build-and-test

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running a build?'
        required: true
        default: 'Manual build'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: 'Print manual build reason'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: nuget
          path: artifacts/package/release/*.nupkg

      - name: Test
        run: dotnet test --configuration Release --no-restore

      - name: Publish
        if: matrix.os == 'ubuntu-latest' && github.ref_type == 'tag'
        run: |
          dotnet nuget push --skip-duplicate artifacts/package/release/*.nupkg \
            --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.NUGET_API_KEY }}"

  test-samples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Build
        run: |
          docker build -f samples/Actions.Core.Sample/Dockerfile . -t actions-core-sample:latest
          docker build -f samples/Actions.Glob.Sample/Dockerfile . -t actions-glob-sample:latest

      - uses: ./samples/Actions.Core.Sample

      - uses: ./samples/Actions.Glob.Sample
        with:
          files: "**/*.cs"
