name: build-and-test

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running a build?'
        required: true
        default: 'Manual build'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: 'Print manual build reason'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: Build
        uses: ./.github/actions/build
        with:
          upload-artifacts: ${{ matrix.os == 'ubuntu-latest' }}

  test-samples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Build
        run: |
          docker build -f samples/Actions.Core.Sample/Dockerfile . -t actions-core-sample:latest
          docker build -f samples/Actions.Glob.Sample/Dockerfile . -t actions-glob-sample:latest

      - uses: ./samples/Actions.Core.Sample

      - uses: ./samples/Actions.Glob.Sample
        with:
          files: "**/*.cs"
