name: publish nuget
on:
  push:
    tags:
      - '**'

jobs: 
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
        - Actions.Core
        - Actions.Octokit
        - Actions.Glob
        #- Actions.IO
    steps:
    
    - name: Print tag ref
      run: echo $GITHUB_REF
      
    - name: Extract version number
      uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.ref }}
        # Extracts the version number from the tag ref: /refs\/tags\/(.+)/
        regex: 'refs\/tags\/(.+)'
       
    - name: Print version number
      run: echo '${{ steps.regex-match.outputs.group1 }}'
      
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        dotnet-quality: 'preview'

    - name: Restore dependencies for ${{ matrix.project }}
      run: |
        dotnet restore ./src/${{ matrix.project }}/${{ matrix.project }}.csproj
      
    - name: Build ${{ matrix.project }}
      run: |
        dotnet build ./src/${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Release --no-restore
    
    - name: Pack ${{ matrix.project }}
      run: |
        dotnet pack ./src/${{ matrix.project }}/${{ matrix.project }}.csproj --output packages
    - name: Upload ${{ matrix.project }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.project }}.${{ steps.regex-match.outputs.group1 }}.nupkg
        path: packages/*.nupkg
      
    - name: Publish ${{ matrix.project }} package
      run: |
        nuget push **\${{ matrix.project }}.*.nupkg -Source 'https://api.nuget.org/v3/index.json' -NoSymbols -NonInteractive -ApiKey ${{secrets.NUGET_API_KEY}}
